# Site settings
title: Steven Teerlinck
email: steven@teerlinck.net
description: "I'm a freelance web developer. I build large web applications and sites using Domain Driven Design, CQRS, Event Sourcing and lots of other tools and methodologies."
baseurl: ""
url: "http://teerlinck.net"
username: steerlin

# Build settings
markdown: kramdown
permalink: pretty
